name: CI workflow
on:
  push:
    branches: push on main branch
  pull_request:
    branches: pull_request on main branch
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Install dependencies
        uses: {placeholder}
      - name: {placeholder}
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
